#**LAB 10 by Sughandhan S, 111901049**

Importing Libraries


In [1]:
import numpy as np

#Optimal "First Batting" Strategy 

In [4]:
prob_out_min = [0.01, 0.02, 0.03, 0.1, 0]

prob_out_max = [0.1, 0.2, 0.3, 0.5, 0]

score = [1,2,3,4,6]

def prob_out(w, a):
  return prob_out_max[a]+ (prob_out_min[a] - prob_out_max[a]) * ( (w-1)/9)

balls = 300
wickets = 10

Best_Score = np.zeros((balls + 1, wickets + 1))
Best_Shot = np.zeros((balls + 1, wickets + 1))
Total_Best_Score = 0 

for b in range(1, balls + 1):
  for w in range(1, wickets + 1):
    lst = []
    for a in range(5):
      lst.append( [(1-prob_out(w, a)) * ( score[a] + Best_Score[b-1][w] ) + prob_out(w,a) *(0+ Best_Score[b-1][w-1]), score[a]] )
    optimum = max(lst)
    Best_Score[b][w] = round(optimum[0],2)
    Best_Shot[b][w] = optimum[1]

print(Best_Score)
print(Best_Shot)

[[   0.    0.    0. ...    0.    0.    0.]
 [   0.    6.    6. ...    6.    6.    6.]
 [   0.   12.   12. ...   12.   12.   12.]
 ...
 [   0. 1788. 1788. ... 1788. 1788. 1788.]
 [   0. 1794. 1794. ... 1794. 1794. 1794.]
 [   0. 1800. 1800. ... 1800. 1800. 1800.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 6. 6. ... 6. 6. 6.]
 [0. 6. 6. ... 6. 6. 6.]
 ...
 [0. 6. 6. ... 6. 6. 6.]
 [0. 6. 6. ... 6. 6. 6.]
 [0. 6. 6. ... 6. 6. 6.]]


In [5]:
print("Balls X Weights -> Best_Score")
for i in Best_Score:
  print(i)

print("Balls X Weights -> Best_Shot")
for i in Best_Shot:
  print(i)

Balls X Weights -> Best_Score
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
[ 0. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
[ 0. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18.]
[ 0. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24.]
[ 0. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30.]
[ 0. 36. 36. 36. 36. 36. 36. 36. 36. 36. 36.]
[ 0. 42. 42. 42. 42. 42. 42. 42. 42. 42. 42.]
[ 0. 48. 48. 48. 48. 48. 48. 48. 48. 48. 48.]
[ 0. 54. 54. 54. 54. 54. 54. 54. 54. 54. 54.]
[ 0. 60. 60. 60. 60. 60. 60. 60. 60. 60. 60.]
[ 0. 66. 66. 66. 66. 66. 66. 66. 66. 66. 66.]
[ 0. 72. 72. 72. 72. 72. 72. 72. 72. 72. 72.]
[ 0. 78. 78. 78. 78. 78. 78. 78. 78. 78. 78.]
[ 0. 84. 84. 84. 84. 84. 84. 84. 84. 84. 84.]
[ 0. 90. 90. 90. 90. 90. 90. 90. 90. 90. 90.]
[ 0. 96. 96. 96. 96. 96. 96. 96. 96. 96. 96.]
[  0. 102. 102. 102. 102. 102. 102. 102. 102. 102. 102.]
[  0. 108. 108. 108. 108. 108. 108. 108. 108. 108. 108.]
[  0. 114. 114. 114. 114. 114. 114. 114. 114. 114. 114.]
[  0. 120. 120. 120. 120. 120. 120. 120