**Lab 3 by Sughandhan S**

#Q1) Finding list of unique words and their count

In [117]:
myfile = open("speechs.txt")

In [118]:
myfile.read()

'Maybe one unisex avatar, with medium-length hair? :)\nCooking & #SandraBullock movie marathon. "A Time to Kill" & "YaYa Sisterhood" ... IMO is one of the most beautiful women ever.\nExcellent, thanks!\nomg yes!!! he was just on punkd I almost died\nLove that moment when you 1st discover a new favorite top or accessory! What was your latest exciting find?\neither of you 2 ever get the chance to actually ride a Mustng? Would love to have the chance.\nBout to go see my ex boyfriend on the big screen ♥`\nWork smarter, not harder.\nof course\nStorytime for kids 5 and under at the Tutt Branch Library every Wednesday in February at 10:30am. Call 282-4637 for more information.\nThank you to everybody at Para Los Ninos and the Thelma Pearl Foundation, the show was fabulous.\ncongrats!! that is awesome!!\nlol I\'m so confused! Are you talking about my butterfly that\'s in the jar?\nGuess who JB follows on Twitter? :)\nScott is one lucky man ..:)\nthx for letting us charge our chevy volt @ ur ma

Reading the file again


In [119]:
myfile.seek(0)
myfile.readlines()

['Maybe one unisex avatar, with medium-length hair? :)\n',
 'Cooking & #SandraBullock movie marathon. "A Time to Kill" & "YaYa Sisterhood" ... IMO is one of the most beautiful women ever.\n',
 'Excellent, thanks!\n',
 'omg yes!!! he was just on punkd I almost died\n',
 'Love that moment when you 1st discover a new favorite top or accessory! What was your latest exciting find?\n',
 'either of you 2 ever get the chance to actually ride a Mustng? Would love to have the chance.\n',
 'Bout to go see my ex boyfriend on the big screen ♥`\n',
 'Work smarter, not harder.\n',
 'of course\n',
 'Storytime for kids 5 and under at the Tutt Branch Library every Wednesday in February at 10:30am. Call 282-4637 for more information.\n',
 'Thank you to everybody at Para Los Ninos and the Thelma Pearl Foundation, the show was fabulous.\n',
 'congrats!! that is awesome!!\n',
 "lol I'm so confused! Are you talking about my butterfly that's in the jar?\n",
 'Guess who JB follows on Twitter? :)\n',
 'Scott is

Going back to the start of the file and storing it in a variable called lines

In [120]:
myfile.seek(0)
lines = myfile.read()

storing the contents of the file into a variable called lines in lower case

In [121]:
lines = lines.lower()
lines

'maybe one unisex avatar, with medium-length hair? :)\ncooking & #sandrabullock movie marathon. "a time to kill" & "yaya sisterhood" ... imo is one of the most beautiful women ever.\nexcellent, thanks!\nomg yes!!! he was just on punkd i almost died\nlove that moment when you 1st discover a new favorite top or accessory! what was your latest exciting find?\neither of you 2 ever get the chance to actually ride a mustng? would love to have the chance.\nbout to go see my ex boyfriend on the big screen ♥`\nwork smarter, not harder.\nof course\nstorytime for kids 5 and under at the tutt branch library every wednesday in february at 10:30am. call 282-4637 for more information.\nthank you to everybody at para los ninos and the thelma pearl foundation, the show was fabulous.\ncongrats!! that is awesome!!\nlol i\'m so confused! are you talking about my butterfly that\'s in the jar?\nguess who jb follows on twitter? :)\nscott is one lucky man ..:)\nthx for letting us charge our chevy volt @ ur ma

Splitting the lines in the textfile into singular words

In [122]:
words =lines.split()

In [123]:
words

['maybe',
 'one',
 'unisex',
 'avatar,',
 'with',
 'medium-length',
 'hair?',
 ':)',
 'cooking',
 '&',
 '#sandrabullock',
 'movie',
 'marathon.',
 '"a',
 'time',
 'to',
 'kill"',
 '&',
 '"yaya',
 'sisterhood"',
 '...',
 'imo',
 'is',
 'one',
 'of',
 'the',
 'most',
 'beautiful',
 'women',
 'ever.',
 'excellent,',
 'thanks!',
 'omg',
 'yes!!!',
 'he',
 'was',
 'just',
 'on',
 'punkd',
 'i',
 'almost',
 'died',
 'love',
 'that',
 'moment',
 'when',
 'you',
 '1st',
 'discover',
 'a',
 'new',
 'favorite',
 'top',
 'or',
 'accessory!',
 'what',
 'was',
 'your',
 'latest',
 'exciting',
 'find?',
 'either',
 'of',
 'you',
 '2',
 'ever',
 'get',
 'the',
 'chance',
 'to',
 'actually',
 'ride',
 'a',
 'mustng?',
 'would',
 'love',
 'to',
 'have',
 'the',
 'chance.',
 'bout',
 'to',
 'go',
 'see',
 'my',
 'ex',
 'boyfriend',
 'on',
 'the',
 'big',
 'screen',
 '♥`',
 'work',
 'smarter,',
 'not',
 'harder.',
 'of',
 'course',
 'storytime',
 'for',
 'kids',
 '5',
 'and',
 'under',
 'at',
 'the',
 't

In [124]:
import string

Table for mapping punctuations to null character

In [125]:
table = str.maketrans('','', string.punctuation)
table

{33: None,
 34: None,
 35: None,
 36: None,
 37: None,
 38: None,
 39: None,
 40: None,
 41: None,
 42: None,
 43: None,
 44: None,
 45: None,
 46: None,
 47: None,
 58: None,
 59: None,
 60: None,
 61: None,
 62: None,
 63: None,
 64: None,
 91: None,
 92: None,
 93: None,
 94: None,
 95: None,
 96: None,
 123: None,
 124: None,
 125: None,
 126: None}

In [126]:
mod_words = [w.translate(table) for w in words]
mod_words

['maybe',
 'one',
 'unisex',
 'avatar',
 'with',
 'mediumlength',
 'hair',
 '',
 'cooking',
 '',
 'sandrabullock',
 'movie',
 'marathon',
 'a',
 'time',
 'to',
 'kill',
 '',
 'yaya',
 'sisterhood',
 '',
 'imo',
 'is',
 'one',
 'of',
 'the',
 'most',
 'beautiful',
 'women',
 'ever',
 'excellent',
 'thanks',
 'omg',
 'yes',
 'he',
 'was',
 'just',
 'on',
 'punkd',
 'i',
 'almost',
 'died',
 'love',
 'that',
 'moment',
 'when',
 'you',
 '1st',
 'discover',
 'a',
 'new',
 'favorite',
 'top',
 'or',
 'accessory',
 'what',
 'was',
 'your',
 'latest',
 'exciting',
 'find',
 'either',
 'of',
 'you',
 '2',
 'ever',
 'get',
 'the',
 'chance',
 'to',
 'actually',
 'ride',
 'a',
 'mustng',
 'would',
 'love',
 'to',
 'have',
 'the',
 'chance',
 'bout',
 'to',
 'go',
 'see',
 'my',
 'ex',
 'boyfriend',
 'on',
 'the',
 'big',
 'screen',
 '♥',
 'work',
 'smarter',
 'not',
 'harder',
 'of',
 'course',
 'storytime',
 'for',
 'kids',
 '5',
 'and',
 'under',
 'at',
 'the',
 'tutt',
 'branch',
 'library',


In [127]:
final_words = [x.strip('') for x in mod_words ]
final_words

['maybe',
 'one',
 'unisex',
 'avatar',
 'with',
 'mediumlength',
 'hair',
 '',
 'cooking',
 '',
 'sandrabullock',
 'movie',
 'marathon',
 'a',
 'time',
 'to',
 'kill',
 '',
 'yaya',
 'sisterhood',
 '',
 'imo',
 'is',
 'one',
 'of',
 'the',
 'most',
 'beautiful',
 'women',
 'ever',
 'excellent',
 'thanks',
 'omg',
 'yes',
 'he',
 'was',
 'just',
 'on',
 'punkd',
 'i',
 'almost',
 'died',
 'love',
 'that',
 'moment',
 'when',
 'you',
 '1st',
 'discover',
 'a',
 'new',
 'favorite',
 'top',
 'or',
 'accessory',
 'what',
 'was',
 'your',
 'latest',
 'exciting',
 'find',
 'either',
 'of',
 'you',
 '2',
 'ever',
 'get',
 'the',
 'chance',
 'to',
 'actually',
 'ride',
 'a',
 'mustng',
 'would',
 'love',
 'to',
 'have',
 'the',
 'chance',
 'bout',
 'to',
 'go',
 'see',
 'my',
 'ex',
 'boyfriend',
 'on',
 'the',
 'big',
 'screen',
 '♥',
 'work',
 'smarter',
 'not',
 'harder',
 'of',
 'course',
 'storytime',
 'for',
 'kids',
 '5',
 'and',
 'under',
 'at',
 'the',
 'tutt',
 'branch',
 'library',


Getting unique list of words


In [128]:
unique_words = set(final_words)

In [129]:
unique_words

{'',
 'ready',
 'julies',
 'jus',
 'movies',
 'science',
 '😄',
 'father',
 'louboutin',
 'its',
 'peril',
 'scratch',
 'joan',
 'latest',
 'myself',
 'swirling',
 'shirt',
 'metz',
 'facebook',
 'hah',
 '21',
 'inspire',
 'date',
 'animal',
 'impressed',
 'fan',
 'collect',
 'daughter',
 'summit',
 'message',
 'hahaha',
 'quiet',
 'storytime',
 'ayye',
 'jb',
 'ya',
 'meetings',
 'w',
 'posted',
 'wasnt',
 'king',
 'rahm',
 'ugh',
 'good',
 'hes',
 'direct',
 'afflicting',
 'cheesy',
 'autograph',
 'contract',
 'name',
 'line',
 'launch',
 'intuitive',
 '21st',
 'otherwise',
 'mad',
 'tweetwoman',
 'tune',
 'come',
 'nate',
 'this',
 '999',
 'preexisting',
 'dang',
 'juss',
 'bad',
 'cubs',
 'talladega',
 'they',
 'whacky',
 'eye',
 'minute',
 '720',
 'wishing',
 'david',
 'both',
 'noise',
 'california',
 'thanks',
 'hit',
 'zero',
 'moving',
 'jokes',
 'firerock',
 'plane',
 'scott',
 'enthusiast',
 'preparing',
 'looked',
 'refreshing',
 'change',
 'say',
 'cancer',
 'dinner',
 'ste

In [130]:
type(final_words)

list

only_words list contains all the words without emojis and punctuations
dictionary list contains all the unique words

In [131]:
only_words = []
dictionary = [] 
for word in final_words:
  letters = list([c for c in word if c.isalpha()])
  word = ''.join(letters)
  if word != '':
    only_words.append(word)
  if word not in dictionary and word!= '':
    dictionary.append(word)

In [132]:
only_words

['maybe',
 'one',
 'unisex',
 'avatar',
 'with',
 'mediumlength',
 'hair',
 'cooking',
 'sandrabullock',
 'movie',
 'marathon',
 'a',
 'time',
 'to',
 'kill',
 'yaya',
 'sisterhood',
 'imo',
 'is',
 'one',
 'of',
 'the',
 'most',
 'beautiful',
 'women',
 'ever',
 'excellent',
 'thanks',
 'omg',
 'yes',
 'he',
 'was',
 'just',
 'on',
 'punkd',
 'i',
 'almost',
 'died',
 'love',
 'that',
 'moment',
 'when',
 'you',
 'st',
 'discover',
 'a',
 'new',
 'favorite',
 'top',
 'or',
 'accessory',
 'what',
 'was',
 'your',
 'latest',
 'exciting',
 'find',
 'either',
 'of',
 'you',
 'ever',
 'get',
 'the',
 'chance',
 'to',
 'actually',
 'ride',
 'a',
 'mustng',
 'would',
 'love',
 'to',
 'have',
 'the',
 'chance',
 'bout',
 'to',
 'go',
 'see',
 'my',
 'ex',
 'boyfriend',
 'on',
 'the',
 'big',
 'screen',
 'work',
 'smarter',
 'not',
 'harder',
 'of',
 'course',
 'storytime',
 'for',
 'kids',
 'and',
 'under',
 'at',
 'the',
 'tutt',
 'branch',
 'library',
 'every',
 'wednesday',
 'in',
 'februa

In [133]:
dictionary

['maybe',
 'one',
 'unisex',
 'avatar',
 'with',
 'mediumlength',
 'hair',
 'cooking',
 'sandrabullock',
 'movie',
 'marathon',
 'a',
 'time',
 'to',
 'kill',
 'yaya',
 'sisterhood',
 'imo',
 'is',
 'of',
 'the',
 'most',
 'beautiful',
 'women',
 'ever',
 'excellent',
 'thanks',
 'omg',
 'yes',
 'he',
 'was',
 'just',
 'on',
 'punkd',
 'i',
 'almost',
 'died',
 'love',
 'that',
 'moment',
 'when',
 'you',
 'st',
 'discover',
 'new',
 'favorite',
 'top',
 'or',
 'accessory',
 'what',
 'your',
 'latest',
 'exciting',
 'find',
 'either',
 'get',
 'chance',
 'actually',
 'ride',
 'mustng',
 'would',
 'have',
 'bout',
 'go',
 'see',
 'my',
 'ex',
 'boyfriend',
 'big',
 'screen',
 'work',
 'smarter',
 'not',
 'harder',
 'course',
 'storytime',
 'for',
 'kids',
 'and',
 'under',
 'at',
 'tutt',
 'branch',
 'library',
 'every',
 'wednesday',
 'in',
 'february',
 'am',
 'call',
 'more',
 'information',
 'thank',
 'everybody',
 'para',
 'los',
 'ninos',
 'thelma',
 'pearl',
 'foundation',
 'show

Number of unique words

In [134]:
len(dictionary)

2148

Total number of words

In [135]:
len(only_words)

6338

Creating a dictionary called m_dict which stores the freq of each word

In [136]:
my_dict = {}
for unq_word in dictionary:
  count=0
  for word in only_words:
    if unq_word==word:
      count+=1
  my_dict[unq_word]=count

In [137]:
my_dict

{'maybe': 3,
 'one': 18,
 'unisex': 1,
 'avatar': 1,
 'with': 34,
 'mediumlength': 1,
 'hair': 3,
 'cooking': 1,
 'sandrabullock': 1,
 'movie': 3,
 'marathon': 1,
 'a': 131,
 'time': 16,
 'to': 162,
 'kill': 1,
 'yaya': 1,
 'sisterhood': 1,
 'imo': 1,
 'is': 67,
 'of': 79,
 'the': 211,
 'most': 4,
 'beautiful': 1,
 'women': 5,
 'ever': 10,
 'excellent': 2,
 'thanks': 26,
 'omg': 5,
 'yes': 7,
 'he': 6,
 'was': 27,
 'just': 33,
 'on': 55,
 'punkd': 1,
 'i': 149,
 'almost': 2,
 'died': 1,
 'love': 24,
 'that': 45,
 'moment': 2,
 'when': 21,
 'you': 128,
 'st': 3,
 'discover': 1,
 'new': 13,
 'favorite': 3,
 'top': 3,
 'or': 25,
 'accessory': 1,
 'what': 25,
 'your': 43,
 'latest': 2,
 'exciting': 2,
 'find': 5,
 'either': 2,
 'get': 23,
 'chance': 2,
 'actually': 2,
 'ride': 1,
 'mustng': 1,
 'would': 14,
 'have': 42,
 'bout': 2,
 'go': 12,
 'see': 13,
 'my': 62,
 'ex': 2,
 'boyfriend': 3,
 'big': 5,
 'screen': 2,
 'work': 5,
 'smarter': 1,
 'not': 21,
 'harder': 1,
 'course': 2,
 'story

In [138]:
len(my_dict)

2148

#Q2) Making an N X N matrix

In [139]:
#importing libraries
import numpy as np
import pandas as pd

2D matrix which will store the freq of occurence of the words in column based on the corresponding word in the row 

In [140]:
Bigram_matix = np.zeros((len(my_dict),len(my_dict)))

In [141]:
Bigram_matix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [142]:
Bigram_matix.shape

(2148, 2148)

A dictionary to store indices for our unique words

In [143]:
indices = {}
x=0
for key in my_dict:
  indices[key]=x
  x+=1 

In [144]:
indices

{'maybe': 0,
 'one': 1,
 'unisex': 2,
 'avatar': 3,
 'with': 4,
 'mediumlength': 5,
 'hair': 6,
 'cooking': 7,
 'sandrabullock': 8,
 'movie': 9,
 'marathon': 10,
 'a': 11,
 'time': 12,
 'to': 13,
 'kill': 14,
 'yaya': 15,
 'sisterhood': 16,
 'imo': 17,
 'is': 18,
 'of': 19,
 'the': 20,
 'most': 21,
 'beautiful': 22,
 'women': 23,
 'ever': 24,
 'excellent': 25,
 'thanks': 26,
 'omg': 27,
 'yes': 28,
 'he': 29,
 'was': 30,
 'just': 31,
 'on': 32,
 'punkd': 33,
 'i': 34,
 'almost': 35,
 'died': 36,
 'love': 37,
 'that': 38,
 'moment': 39,
 'when': 40,
 'you': 41,
 'st': 42,
 'discover': 43,
 'new': 44,
 'favorite': 45,
 'top': 46,
 'or': 47,
 'accessory': 48,
 'what': 49,
 'your': 50,
 'latest': 51,
 'exciting': 52,
 'find': 53,
 'either': 54,
 'get': 55,
 'chance': 56,
 'actually': 57,
 'ride': 58,
 'mustng': 59,
 'would': 60,
 'have': 61,
 'bout': 62,
 'go': 63,
 'see': 64,
 'my': 65,
 'ex': 66,
 'boyfriend': 67,
 'big': 68,
 'screen': 69,
 'work': 70,
 'smarter': 71,
 'not': 72,
 'hard

index mapping to words


In [145]:
index_to_words = {}
x=0
for key in my_dict:
  index_to_words[x]=key
  x+=1 

In [146]:
index_to_words

{0: 'maybe',
 1: 'one',
 2: 'unisex',
 3: 'avatar',
 4: 'with',
 5: 'mediumlength',
 6: 'hair',
 7: 'cooking',
 8: 'sandrabullock',
 9: 'movie',
 10: 'marathon',
 11: 'a',
 12: 'time',
 13: 'to',
 14: 'kill',
 15: 'yaya',
 16: 'sisterhood',
 17: 'imo',
 18: 'is',
 19: 'of',
 20: 'the',
 21: 'most',
 22: 'beautiful',
 23: 'women',
 24: 'ever',
 25: 'excellent',
 26: 'thanks',
 27: 'omg',
 28: 'yes',
 29: 'he',
 30: 'was',
 31: 'just',
 32: 'on',
 33: 'punkd',
 34: 'i',
 35: 'almost',
 36: 'died',
 37: 'love',
 38: 'that',
 39: 'moment',
 40: 'when',
 41: 'you',
 42: 'st',
 43: 'discover',
 44: 'new',
 45: 'favorite',
 46: 'top',
 47: 'or',
 48: 'accessory',
 49: 'what',
 50: 'your',
 51: 'latest',
 52: 'exciting',
 53: 'find',
 54: 'either',
 55: 'get',
 56: 'chance',
 57: 'actually',
 58: 'ride',
 59: 'mustng',
 60: 'would',
 61: 'have',
 62: 'bout',
 63: 'go',
 64: 'see',
 65: 'my',
 66: 'ex',
 67: 'boyfriend',
 68: 'big',
 69: 'screen',
 70: 'work',
 71: 'smarter',
 72: 'not',
 73: '

In [147]:
for key in my_dict:
  flag = 0
  for word in only_words:
    if flag ==1:
      Bigram_matix[indices[key]][indices[word]]= Bigram_matix[indices[key]][indices[word]] + 1
      flag=0
    if key==word:
      flag=1

Some rough work for testing code

In [148]:
Bigram_matix[0][0]

0.0

In [149]:
indices["maybe"]

0

In [150]:
Bigram_matix[indices['maybe']][indices['one']]

1.0

In [151]:
Bigram_matix[7][8]

1.0

In [152]:
Bigram_matix

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

Checking if there are any entires greater than 1 for word 'a'

In [153]:
indices['a']

11

In [154]:
lst = []
for i in range(2148):
  if Bigram_matix[11][i]>1:
    print(Bigram_matix[11][i])
    lst.append(i)

2.0
2.0
2.0
2.0
2.0
2.0
8.0
3.0
3.0
2.0


In [155]:
#words appearing after 'a' with frequency >1
for y in lst:
  print(index_to_words[y])

new
big
few
higher
while
book
great
little
lot
huge


Functio to print frequency of occurence of next word based on the given word

In [156]:
def freq_of_occurence(word):
  print('Given word is',word)
  for i in indices:
    print('Frequency of occurence of', i,' is :', Bigram_matix[indices[word]][indices[i]])
  return Bigram_matix[indices[word]]



#talking

In [157]:
talking = freq_of_occurence('talking')
print(talking)

Given word is talking
Frequency of occurence of maybe  is : 0.0
Frequency of occurence of one  is : 0.0
Frequency of occurence of unisex  is : 0.0
Frequency of occurence of avatar  is : 0.0
Frequency of occurence of with  is : 0.0
Frequency of occurence of mediumlength  is : 0.0
Frequency of occurence of hair  is : 0.0
Frequency of occurence of cooking  is : 0.0
Frequency of occurence of sandrabullock  is : 0.0
Frequency of occurence of movie  is : 0.0
Frequency of occurence of marathon  is : 0.0
Frequency of occurence of a  is : 0.0
Frequency of occurence of time  is : 0.0
Frequency of occurence of to  is : 3.0
Frequency of occurence of kill  is : 0.0
Frequency of occurence of yaya  is : 0.0
Frequency of occurence of sisterhood  is : 0.0
Frequency of occurence of imo  is : 0.0
Frequency of occurence of is  is : 0.0
Frequency of occurence of of  is : 0.0
Frequency of occurence of the  is : 0.0
Frequency of occurence of most  is : 0.0
Frequency of occurence of beautiful  is : 0.0
Freque

In [158]:
row = freq_of_occurence('a')

Given word is a
Frequency of occurence of maybe  is : 0.0
Frequency of occurence of one  is : 0.0
Frequency of occurence of unisex  is : 0.0
Frequency of occurence of avatar  is : 0.0
Frequency of occurence of with  is : 0.0
Frequency of occurence of mediumlength  is : 0.0
Frequency of occurence of hair  is : 0.0
Frequency of occurence of cooking  is : 0.0
Frequency of occurence of sandrabullock  is : 0.0
Frequency of occurence of movie  is : 0.0
Frequency of occurence of marathon  is : 0.0
Frequency of occurence of a  is : 0.0
Frequency of occurence of time  is : 1.0
Frequency of occurence of to  is : 0.0
Frequency of occurence of kill  is : 0.0
Frequency of occurence of yaya  is : 0.0
Frequency of occurence of sisterhood  is : 0.0
Frequency of occurence of imo  is : 0.0
Frequency of occurence of is  is : 0.0
Frequency of occurence of of  is : 0.0
Frequency of occurence of the  is : 0.0
Frequency of occurence of most  is : 0.0
Frequency of occurence of beautiful  is : 0.0
Frequency of

In [159]:
print(row)

[0. 0. 0. ... 0. 0. 0.]


In [160]:
cumulative_freq_rowwise = Bigram_matix.sum(axis = 1)
cumulative_freq_rowwise= np.array(cumulative_freq_rowwise)

In [161]:
cumulative_freq_rowwise

array([ 3., 18.,  1., ...,  1.,  1.,  0.])

In [162]:
type(cumulative_freq_rowwise)

numpy.ndarray

Rough work

In [163]:
f=0
g=0
for i in range(len(my_dict)):
  f+=Bigram_matix[0][i]
  g+=Bigram_matix[1][i]
print(f)
print(g)

3.0
18.0


#Q3) Generating 1000 funny words

Printing funny texts(random model)

In [164]:
funny_texts = ''

In [165]:
start = np.random.randint(len(my_dict))
start

48

In [166]:
index_to_words[start]

'accessory'

In [167]:
cumulative_freq_rowwise[start]

1.0

In [168]:
next_word = np.random.random()*cumulative_freq_rowwise[start]
next_word

0.6506820853221109

In [169]:
Bigram_matix[start]

array([0., 0., 0., ..., 0., 0., 0.])

In [170]:
Bigram_matix[start][0]

0.0

In [171]:
num=1000
funny_texts = ''
start = 0
flag=0
while num>0:
  if flag==0:
    start = np.random.randint(len(my_dict))
    funny_texts+= index_to_words[start]
    funny_texts+=' '
    flag=1
    num=num-1
  else:
    next_word = np.random.random()*cumulative_freq_rowwise[start]
    freq_sum=0
    for i in range(len(my_dict)):
      freq_sum+= Bigram_matix[start][i]
      if freq_sum>= next_word:
        funny_texts+= index_to_words[i]
        funny_texts+=' '
        start = i
        break
    if freq_sum>= next_word:
      num =num-1
    else: 
      flag=0



    # if target==0:
    #   flag=0
    # else:
    #   count = 0
    #   possible_indices=[]
    #   for i in range(len(my_dict)):
    #     if Bigram_matix[start][i] == target:
    #       possible_indices.append(i)
    #       count = count+1
    #   prediction_index = np.random.randint(count)
    #   start = possible_indices[prediction_index]
    #   funny_texts+= index_to_words[start]
    #   funny_texts+=' '
    #   num= num-1

In [172]:
print(funny_texts)

nothin to hell waiting on a motorcycle shop pinup shoot is to rock n roll yea im always amazed when uninspired cos realize they get the mail it works out chest hes insecure and i love you think cant repond to watch it on it would have the video talk about his contract im bummed im here comes a milestone for heat vs spurs in the market all thanks for mention geometry i know more important than composite wowyet again lol thanks for detail people would rather have one yehh got a stock drops in to dance in school aww yay battleship whatever is over miami holy shit with us data the curious caught my music shoppe guided workout with my bday im not sleeping or what my new home now heaven is oct th be square love the keyboard that u doing it get the gap im fine the party lol that posted today i quit thanks nick i piss in pa study finds schools is k byee lmfao calm down to make a fishing pole answer to say i need to accomplish before you all just make sure if not have very witty say it need sbs

This version of printing texts is less random and more focused on relative probability of occurence of the next word based on the given word

In [174]:
target_freq = Bigram_matix.max(axis=1)

In [177]:
funny_texts=''
start = 0
flag=0
num=1000
while num>0:
  if flag==0:
    start = np.random.randint(len(my_dict))
    funny_texts+= index_to_words[start]
    funny_texts+=' '
    flag=1
    num=num-1
  else:
    target = target_freq[start]
    if target==0:
      flag=0
    else:
      count = 0
      possible_indices=[]
      for i in range(len(my_dict)):
        if Bigram_matix[start][i] == target:
          possible_indices.append(i)
          count = count+1
      prediction_index = np.random.randint(count)
      start = possible_indices[prediction_index]
      funny_texts+= index_to_words[start]
      funny_texts+=' '
      num= num-1

        




In [178]:
print(funny_texts)

latin america rhetorical tweets should i am i am i am so much fun when i am so much fun having a great day the best friend don swayze in the best friend i am not a great day once in the day once and i am i am i am i am so much more i am not good luck as i am not know what do you have a great week d its a great week when i am not saving me i am i am not let me i am i am not until i am i am i am not sleeping or not torres working on the day asshole rt i am not know what you have a great week when i am so much fun god please explain to the best friend i am so much more i am so much fun date with my friend and i am i am i am not saving me i am i am not have a great day once and i am not better than a great day super bowl rather be a great week than that was a great day it was a great day until i am not know what a great day biscuits thank you have a great week d lmfao calm down to the best friend in the best friend in the day asshole rt i am so much more i am not sleeping or not a great da